truncate prefecture;
insert into prefecture(
	prefecture_id,				
	prefecture_name,				
	del_flg					
) values (						
	01	,	'北海道'	,	false	),
(	02	,	'青森県'	,	false	),
(	03	,	'岩手県'	,	false	),
(	04	,	'宮城県'	,	false	),
(	05	,	'秋田県'	,	false	),
(	06	,	'山形県'	,	false	),
(	07	,	'福島県'	,	false	),
(	08	,	'茨城県'	,	false	),
(	09	,	'栃木県'	,	false	),
(	10	,	'群馬県'	,	false	),
(	11	,	'埼玉県'	,	false	),
(	12	,	'千葉県'	,	false	),
(	13	,	'東京都' ,	false	),
(	14	,	'神奈川県',	false	),
(	15	,	'新潟県'	,	false	),
(	16	,	'富山県'	,	false	),
(	17	,	'石川県'	,	false	),
(	18	,	'福井県'	,	false	),
(	19	,	'山梨県'	,	false	),
(	20	,	'長野県'	,	false	),
(	21	,	'岐阜県'	,	false	),
(	22	,	'静岡県'	,	false	),
(	23	,	'愛知県'	,	false	),
(	24	,	'三重県'	,	false	),
(	25	,	'滋賀県'	,	false	),
(	26	,	'京都府'	,	false	),
(	27	,	'大阪府'	,	false	),
(	28	,	'兵庫県'	,	false	),
(	29	,	'奈良県'	,	false	),
(	30	,	'和歌山県',	false	),
(	31	,	'鳥取県'	,	false	),
(	32	,	'島根県'	,	false	),
(	33	,	'岡山県'	,	false	),
(	34	,	'広島県'	,	false	),
(	35	,	'山口県'	,	false	),
(	36	,	'徳島県'	,	false	),
(	37	,	'香川県'	,	false	),
(	38	,	'愛媛県'	,	false	),
(	39	,	'高知県'	,	false	),
(	40	,	'福岡県'	,	false	),
(	41	,	'佐賀県'	,	false	),
(	42	,	'長崎県'	,	false	),
(	43	,	'熊本県'	,	false	),
(	44	,	'大分県'	,	false	),
(	45	,	'宮崎県'	,	false	),
(	46	,	'鹿児島県',	false	),
(	47	,	'沖縄県'	,	false	);